/* **************************************************************************************
Copyright (c) Microsoft Open Technologies, Inc. All rights reserved. Licensed under the Apache License, Version 2.0. 
See License.txt in the project root for license information.
***************************************************************************************** */

var ScriptsResources = {
    BackButtonTitle: "Back",
    BindingPaneButtonCancel: "Cancel",
    BindingPaneButtonOK: "Create",
    BindingPaneInfoDataSetTooLarge: "The data range you selected is too large for the app.",
    BindingPaneInfoFirstColumnEmpty: "The first column shouldn't be empty.",
    BindingPaneInfoFirstRowEmpty: "The first row shouldn’t be empty.",
    BindingPaneInfoMaxColumn: "Although {0} {1} and {2} {3} are selected, the chart can only show the first {4} {5}.",
    BindingPaneInfoMaxRow: "Although {0} {1} and {2} {3} are selected, the chart can only show the first {4} {5}.",
    BindingPaneInfoMaxRowAndColumn: "Although {0} {1} and {2} {3} are selected, the chart can only show the first {4} {5} and the first {6} {7}.",
    BindingPaneInfoNormal: "You've selected {0} {1} and {2} {3}.",
    BindingPaneInfoSecondColumnContainNumber: "Any cell of the second column except for the header should contain a number.",
    BindingPaneInfoSelectData: "Please select your data area in the Excel spreadsheet.",
    BindingPaneInfoSelectTwoColumns: "Please select at least two columns. The data in the first column will be shown on the x-axis.",
    BindingPaneSampleDataHeader1: "Time",
    BindingPaneSampleDataHeader2: "Computers",
    BindingPaneSampleDataHeader3: "Mobile devices",
    BindingPaneSampleDataTime1: "0:00",
    BindingPaneSampleDataTime2: "3:00",
    BindingPaneSampleDataTime3: "6:00",
    BindingPaneSubtitle: "SAMPLE DATA",
    BindingPaneTitle: "Select your data to create a chart",
    DataPaneHeader: "Data",
    DataPaneSelectButton: "Select your data",
    DefaultLegendName: "Line {0}",
    FloatMenuDataTitle: "Data",
    FloatMenuSettingTitle: "Settings",
    PluralizationColumns: "column||columns",
    PluralizationRows: "row||rows",
    SampleDataLegend1: "Computers",
    SampleDataLegend2: "Mobile devices",
    SampleDataLongDescription: "People prefer to use PCs  at work, and surf the Internet via mobile devices at their leisure.",
    SampleDataLongDescriptionTitle: "Data analysis",
    SampleDataShortDescription: "148,000",
    SampleDataShortDescriptionTitle: "afternoon the PC traffic peak time",
    SampleDataTime1: "0:00",
    SampleDataTime2: "3:00",
    SampleDataTime3: "6:00",
    SampleDataTime4: "9:00",
    SampleDataTime5: "12:00",
    SampleDataTime6: "15:00",
    SampleDataTime7: "18:00",
    SampleDataTime8: "21:00",
    SampleDataTime9: "23:00",
    SampleDataTitle: "Website Traffic Analysis",
    SettingPaneHeader: "Settings",
    SettingPaneThemeTab: "Theme",
    SettingPaneThemeTitle1: "Theme 1",
    SettingPaneThemeTitle2: "Theme 2",
    SettingPaneThemeTitle3: "Theme 3",
    SettingPaneThemeTitle4: "Theme 4",
    SettingPaneThemeTitle5: "Theme 5",
    SettingPaneThemeTitle6: "Theme 6",
};