/* **************************************************************************************
Copyright (c) Microsoft Open Technologies, Inc. All rights reserved. 
Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
***************************************************************************************** */

var ScriptsResources = {
    BackButtonTitle: "Back",
    BindingPaneCancelButton: "Cancel",
    BindingPaneInfoDataSetTooLarge: "The data range you selected is too large for the app.",
    BindingPaneInfoFirstColumnEmpty: "The first column shouldn't be empty.",
    BindingPaneInfoFirstRowEmpty: "The first row shouldn't be empty.",
    BindingPaneInfoMaxColumn: "Although {0} {1} and {2} {3} are selected, the chart can only show the first {4} {5}.",
    BindingPaneInfoMaxRow: "Although {0} {1} and {2} {3} are selected, the chart can only show the first {4} {5}.",
    BindingPaneInfoMaxRowAndColumn: "Although {0} {1} and {2} {3} are selected, the chart can only show the first {4} {5} and the first {6} {7}.",
    BindingPaneInfoNormal: "You've selected {0} {1} and {2} {3}.",  
    BindingPaneInfoSecondColumnContainNumber: "Any cell of the second column except for the header should contain a number.",
    BindingPaneInfoSelectData: "Please select your data area in the Excel spreadsheet.",
    BindingPaneInfoSelectTwoColumns: "Please select two columns in your Excel spreadsheet.",
    BindingPaneOKButton: "Create",
    BindingPaneSubtitle: "SAMPLE DATA",
    BindingPaneTitle: "Select your data to create a chart",
    DataPaneEditTitleLabel: "Title",
    DataPaneHeader: "Data",
    DataPaneSelectButton: "Select your data",
    EditTitle: "Double-click to edit the title",
    FloatMenuDataTitle: "Data",
    FloatMenuSettingTitle: "Settings",
    NotificationDontShowAgainButton: "Don't show again",
    NotificationExtendAppToShowMore: "Please extend your app to show more data.",
    PluralizationColumns: "column||columns",
    PluralizationRows: "row||rows",
    SampleDataCalloutRow1: "Purchase a smart phone",
    SampleDataCalloutRow2: "Take a summer course",
    SampleDataCalloutRow3: "Take a part time job",
    SampleDataCalloutTitle: "What do students do in summer?",
    SampleDataClassicRow1: "Shopping",
    SampleDataClassicRow2: "Entertainment",
    SampleDataClassicRow3: "Dining",
    SampleDataClassicTitle: "What do people do after work?",
    SampleDataGaintRow1: "Average clicks per day",
    SampleDataGaintRow2: "Total downloads from store",
    SampleDataGaintRow3: "Number of revisits within a month",
    SampleDataGaintTitle: "NUMBERS ABOUT THE APP",
    SettingPaneShapeTitle14: "Shape 14",
    SettingPaneHeader: "Settings",
    SettingPaneShapeTab: "shape",
    SettingPaneShapeTitle1: "Shape 1",
    SettingPaneShapeTitle2: "Shape 2",
    SettingPaneShapeTitle3: "Shape 3",
    SettingPaneShapeTitle4: "Shape 4",
    SettingPaneShapeTitle5: "Shape 5",
    SettingPaneShapeTitle6: "Shape 6",
    SettingPaneShapeTitle7: "Shape 7",
    SettingPaneShapeTitle8: "Shape 8",
    SettingPaneShapeTitle9: "Shape 9",
    SettingPaneShapeTitle10: "Shape 10",
    SettingPaneShapeTitle11: "Shape 11",
    SettingPaneShapeTitle12: "Shape 12",
    SettingPaneShapeTitle13: "Shape 13",
    SettingPaneShapeTitle15: "Shape 15",
    SettingPaneShapeTitle16: "Shape 16",
    SettingPaneThemeTab: "theme",
    SettingPaneThemeTitle1: "Theme 1",
    SettingPaneThemeTitle2: "Theme 2",
    SettingPaneThemeTitle3: "Theme 3",
    SettingPaneThemeTitle4: "Theme 4",
    SettingPaneThemeTitle5: "Theme 5",
    SettingPaneThemeTitle6: "Theme 6",
    SettingPaneThemeTitle7: "Theme 7",
    SettingPaneTypeTab: "type",
    SettingPaneTypeGaintTitle: "Type 1",
    SettingPaneTypeCalloutTitle: "Type 2",
    SettingPaneTypeClassicTitle: "Type 3",   
};